#!/bin/bash
set -e

# Autogenerated. Do not modify.
# This script was generated by generate-installation-script.sh.

# Configuration with sane defaults
# Users can override these via environment variables or command-line arguments
BINARY_NAME="meroctl"
VERSION="${VERSION:-0.10.0-rc.28}"
REPO="${REPO:-calimero-network/core}"
INSTALL_DIR="${INSTALL_DIR:-$HOME/.local/bin}"

# Parse command-line arguments
while [[ $# -gt 0 ]]; do
  case $1 in
    --version)
      if [[ -z "$2" || "$2" == --* ]]; then
        echo "Error: --version requires a value"
        exit 1
      fi
      VERSION="$2"
      shift 2
      ;;
    --install-dir)
      if [[ -z "$2" || "$2" == --* ]]; then
        echo "Error: --install-dir requires a value"
        exit 1
      fi
      INSTALL_DIR="$2"
      shift 2
      ;;
    --repo)
      if [[ -z "$2" || "$2" == --* ]]; then
        echo "Error: --repo requires a value"
        exit 1
      fi
      REPO="$2"
      shift 2
      ;;
    --help)
      echo "Usage: $0 [OPTIONS]"
      echo ""
      echo "Options:"
      echo "  --version VERSION        Set the version to install (default: 0.10.0-rc.28)"
      echo "  --install-dir DIR        Set the installation directory (default: \$HOME/.local/bin)"
      echo "  --repo REPO              Set the GitHub repository (default: calimero-network/core)"
      echo "  --help                   Display this help message"
      echo ""
      echo "Environment variables:"
      echo "  VERSION                  Same as --version"
      echo "  INSTALL_DIR              Same as --install-dir"
      echo "  REPO                     Same as --repo"
      exit 0
      ;;
    *)
      echo "Unknown option: $1"
      echo "Run '$0 --help' for usage information."
      exit 1
      ;;
  esac
done

# Detect OS and Architecture
OS=$(uname | tr '[:upper:]' '[:lower:]')
ARCH=$(uname -m)

case "$ARCH" in
  "x86_64") ARCH="x86_64" ;;
  "arm64" | "aarch64") ARCH="aarch64" ;;
  *)
    echo "Unsupported architecture: $ARCH."
    exit 1
    ;;
esac

if [ "$OS" == "darwin" ]; then
  PLATFORM="apple-darwin"
elif [ "$OS" == "linux" ]; then
  PLATFORM="unknown-linux-gnu"
else
  echo "Unsupported operating system: $OS."
  exit 1
fi

# Construct download URL
TARBALL_NAME="${BINARY_NAME}_${ARCH}-${PLATFORM}.tar.gz"
DOWNLOAD_URL="https://github.com/${REPO}/releases/download/${VERSION}/${TARBALL_NAME}"

# Ensure installation directory exists
mkdir -p "$INSTALL_DIR"

# Resolve INSTALL_DIR to absolute path
INSTALL_DIR="$(cd "$INSTALL_DIR" && pwd)"

# Download binary tarball
echo "Downloading $TARBALL_NAME ..."
curl -sSL -o "$TARBALL_NAME" "$DOWNLOAD_URL"

# Extract binary
echo "Extracting $TARBALL_NAME ..."
tar -xzf "$TARBALL_NAME"
chmod +x "$BINARY_NAME"

# Move binary to user-local bin directory
mv "$BINARY_NAME" "$INSTALL_DIR/$BINARY_NAME"
rm "$TARBALL_NAME"

echo "Installed $BINARY_NAME successfully in '$INSTALL_DIR'"
echo ""

# Check if install directory is in PATH
if ! echo "$PATH" | grep -q "$INSTALL_DIR"; then
  # Detect shell and set appropriate config file
  SHELL_CONFIG_FILE="$HOME/.bashrc"
  EXPORT_CMD="export PATH=\"$INSTALL_DIR:\$PATH\""

  case "$SHELL" in
    */zsh)
      SHELL_CONFIG_FILE="$HOME/.zshrc"
      ;;
    */fish)
      SHELL_CONFIG_FILE="$HOME/.config/fish/config.fish"
      EXPORT_CMD="set -gx PATH \"$INSTALL_DIR\" \$PATH"
      ;;
    */csh|*/tcsh)
      SHELL_CONFIG_FILE="$HOME/.cshrc"
      EXPORT_CMD="setenv PATH \"$INSTALL_DIR:\$PATH\""
      ;;
  esac

  echo "WARNING: $INSTALL_DIR is not in your PATH"
  echo ""
  echo "To add it to your PATH, run:"
  echo ""
  echo "  echo '$EXPORT_CMD' >> $SHELL_CONFIG_FILE"
  echo "  source $SHELL_CONFIG_FILE"
  echo ""
else
  echo "Verify installation by running:"
  echo ""
  echo "  $BINARY_NAME --version"
  echo ""
fi
